import type { Metadata } from "next";
import Link from "next/link";
import styles from "./layout.module.sass";
import { Button } from "@/components/ui/button";
import { MehOutlined, TeamOutlined } from "@ant-design/icons";
import "./globals.css";
import cx from "classnames";
import { ConfigProvider } from "antd";
import BroadCast from "@/components/Broadcast";
import MotionBackground from "@/components/Motion";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const info = await fetch("http://127.0.0.1:3000/api/rcon/info");
  const result = await info.json();
  return (
    <html lang="en">
      <body>
        <div className="grid h-screen w-full lg:grid-cols-[260px_1fr]">
          <div className="hidden lg:flex flex-col border-r bg-gray-100/40 dark:bg-gray-800/40">
            <div className="flex h-[60px] items-center px-6">
              <Link
                className="flex items-center gap-2 text-xl font-semibold"
                href="#"
              >
                <span>Palworld INC.</span>
              </Link>
            </div>
            <div className="flex-1 overflow-auto py-4">
              <nav className="grid gap-1 px-6">
                <Link
                  className="flex items-center h-10 px-4 rounded-md bg-gray-100/50 text-sm font-medium transition-colors hover:bg-gray-100 dark:bg-gray-800 hover:text-gray-900 dark:text-gray-50"
                  href="/players"
                >
                  <MehOutlined className="mr-2 h-4 w-4" />
                  Players
                </Link>
                <Link
                  className="flex items-center h-10 px-4 rounded-md bg-gray-100/50 text-sm font-medium transition-colors hover:bg-gray-100 dark:bg-gray-800 hover:text-gray-900 dark:text-gray-50"
                  href="/guilds"
                >
                  <TeamOutlined className="mr-2 h-4 w-4" />
                  Guilds
                </Link>
              </nav>
            </div>
          </div>
          <MotionBackground />
          <div className={cx("flex flex-col min-h-screen", styles.main)}>
            <div className="flex h-[60px] items-center border-b px-4 md:px-6">
              <Button className="mr-4 rounded-full sm:hidden">
                <MehOutlined className="w-4 h-4" />
                <span className="sr-only">Toggle sidebar</span>
              </Button>
              <div className={`flex-1 ${styles.header}`}>
                <span className={styles.serverInfo}>
                  {result.ver} {result.name}
                </span>
              </div>
              <BroadCast />
            </div>
            <main className="flex-1 overflow-y-auto">
              <div className="container px-4 py-6 sm:px-6 sm:py-8 lg:px-8">
                <ConfigProvider>{children}</ConfigProvider>
              </div>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
